version: "3.9"
services: 
    app:
        build: ./infra/php
        volumes:
            - ./backend:/work

    #追記 nginx
    web:
        image: nginx:1.20-alpine
        ports:
            - 8080:80
        volumes: 
            - ./backend:/work
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /work

    #mysql 設定
    db:
        build: ./infra/mysql
        volumes: 
            - db-store:/var/lib/mysql

    #mail 設定[MailHog] 2021/05/21
    mail:
        image: mailhog/mailhog
        ports: 
            - 8025:8025

    #phpmyadmin 設定 2021/05/21
    pma:
        image: phpmyadmin/phpmyadmin
        environment: 
            - PMA_HOST=db
            - PMA_USER=phper
            - PMA_PASSWORD=secret
        ports: 
            - 8081:80
        volumes: 
            - pma-session-store:/sessions

volumes:
    db-store:
    #phpmyadmin　volumes
    pma-session-store:
